### ISSUE TITLE
#scrollytellerWAYPOINT50 still triggers mark at 80%

### ISSUE THREAD

**Issue by phocks** [abcnews/scrollyteller#29]
I'm on `"@abcnews/scrollyteller": "^2.2.1",`

Using #scrollytellerWAYPOINT50 in Core. Marker is still being fired at 80% down screen.

(could be just me, but marking it as an issue in case)

![Windows_10_Core__Running_](https://user-images.githubusercontent.com/437566/94211806-d881c200-ff15-11ea-8916-c96e43fa9713.png)
![Access_denied_-_ABC_News__Australian_Broadcasting_Corporation_](https://user-images.githubusercontent.com/437566/94211808-d9b2ef00-ff15-11ea-94fc-90a74b36c474.png)

**Comment by drzax** [comment]
Yeah, I can't see how that ever would have worked. Is there a compelling use case for making it possible to set the waypoint from Core? I'd be leaning towards taking it out all together and specifying it in code:

```jsx
<Scrollyteller config={{waypoint: 50}} ... >
```
And if we're not specifying it in core I'd be tempted to divide that by 100 for the 4.0 release: `waypoint: 0.5`. It's only a whole number so it works with hash markers (which, as we've just established, it doesn't).

**Comment by drzax** [comment]
I'm going to implement the change above today unless I hear a compelling argument to keep (i.e. re-implement) the ability to define the waypoint in the `#scrollyteller` marker.

**Comment by phocks** [comment]
Yep cool. Makes sense to just have it in the code as `0.5`

**Comment by drzax** [comment]
Turns out I left this in. It made sense to keep it after I'd properly
sorted out the separation of config variables and data when processing the
objects parsed out of hash markers.
