### ISSUE TITLE
Subsequent #mark tags with no values take on value from previous #mark?

### ISSUE THREAD

**Issue by phocks** [abcnews/scrollyteller#4]
This might be a feature not a bug perhaps??? But...

```
#scrollyteller
This is the change in global temperature since 1910.
As you can see there has been a pretty drastic increase in temperature.
#mark
But what about in your lifetime?
#markTRIGGERfade
...
#mark
....
#markTESTvalue
This is what's happened in your life. From 1978 to 2018.
#mark
But what does this mean?
#endscrollyteller
```

Produces this in console when we scroll down 

```
{piecemeal: false}
{piecemeal: false}
{trigger: "fade", hash: "TRIGGERfade", piecemeal: false}
{trigger: "fade", hash: "TRIGGERfade", piecemeal: false}
{test: "value", hash: "TESTvalue", piecemeal: false}
{test: "value", hash: "TESTvalue", piecemeal: false}
```

When I would have expected it to produce

```
{piecemeal: false}
{piecemeal: false}
{trigger: "fade", hash: "TRIGGERfade", piecemeal: false}
{piecemeal: false}
{test: "value", hash: "TESTvalue", piecemeal: false}
{piecemeal: false}
```

Anyway I just thought I'd log it here for discussion. It's not really a problem, just thought it was odd.

**Comment by phocks** [comment]
Note: yes this is easily fixed by making sure you put a value on the #mark

**Comment by nathanhoad** [comment]
This is intended behavior. Unless you explicitly specify config for a marker it will assume the config from the previous marker still stands. It is copied to make referencing values simpler (removing the need to manually work out what the previous marker was at run time).
